// <auto-generated />
using FinanceDataTool.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceDataTool.Migrations
{
    [DbContext(typeof(FinanceContext))]
    [Migration("20260728020513_AddLastFetchedUnix")]
    partial class AddLastFetchedUnix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("FinanceDataTool.Core.Holding", b =>
                {
                    b.Property<long>("StockRecnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvgPurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Shares")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StockRecnum");

                    b.HasIndex("Symbol");

                    b.ToTable("Holding", (string)null);
                });

            modelBuilder.Entity("FinanceDataTool.Core.Stock", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Change")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HighPrice")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastFetchedUnix")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LowPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OpenPrice")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PercentageChange")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("PreviousClose")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Symbol");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FinanceDataTool.Core.SystemInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DbVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastUpdated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("System", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DbVersion = 0L
                        });
                });

            modelBuilder.Entity("FinanceDataTool.Core.Holding", b =>
                {
                    b.HasOne("FinanceDataTool.Core.Stock", null)
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
