// <auto-generated />
using FinanceDataTool;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceDataTool.Migrations
{
    [DbContext(typeof(FinanceContext))]
    partial class FinanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("FinanceDataTool.Holding", b =>
                {
                    b.Property<long>("StockRecnum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgPurchasePrice")
                        .HasColumnType("REAL");

                    b.Property<double>("Shares")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StockRecnum");

                    b.HasIndex("Symbol");

                    b.ToTable("Holding", (string)null);
                });

            modelBuilder.Entity("FinanceDataTool.Stock", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Change")
                        .HasColumnType("REAL");

                    b.Property<double?>("CurrentPrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("HighPrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("LowPrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("OpenPrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("PercentageChange")
                        .HasColumnType("REAL");

                    b.Property<double?>("PreviousClose")
                        .HasColumnType("REAL");

                    b.Property<long?>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Symbol");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FinanceDataTool.SystemInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DbVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastUpdated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("System", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DbVersion = 0L
                        });
                });

            modelBuilder.Entity("FinanceDataTool.Holding", b =>
                {
                    b.HasOne("FinanceDataTool.Stock", null)
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
